
sudo: required
cache:
  apt: true
  ccache: true
  directories:
    - $HOME/.ccache
    - /tmp/beam_dependencies

# Specify what combinations of Ubuntu/ROS we want to build
# Limited to what is available on Travis VMs.
language: generic
matrix:
  allow_failures:
    - env: CHECK_COMMIT_FORMAT=ON
  include:
    - name: "Xenial kinetic"
      dist: xenial
      env: ROS_DISTRO=kinetic

################################################################################
env:
  global:
    - CI_SOURCE_PATH=$(pwd)
    - CONTINUOUS_INTEGRATION='True'

# Check installation script
script:
  - cd $CI_SOURCE_PATH
  - ls
  - bash ./scripts/install.bash
  - cd $HOME/catkin_ws/build/libbeam/
  - ./beam_calibration/beam_calibration_extrinsics_tests
  - ./beam_calibration/beam_calibration_intrinsic_tests
  - ./beam_defects/beam_defects_delam_tests
  - ./beam_defects/beam_defects_spall_tests
