# Specify generic linux distribution of linux
language: generic
dist: xenial
sudo: required

# Setup build cache
cache:
  apt: true
  ccache: true
  directories:
    - $HOME/.ccache
    - /tmp/beam_dependencies

# Set global variables
env:
  global:
    - CI_SOURCE_PATH=$(pwd)
    - CONTINUOUS_INTEGRATION='True'

# Check installation script
install:
  - cd $CI_SOURCE_PATH
  - travis_wait 120 bash ./scripts/install.bash

# Run unit test scripts
jobs:
  include: 
    - stage: beam_calibration_tests
    script: cd $HOME/catkin_ws/build/libbeam/beam_calibration
    script: ./beam_calibration_extrinsics_tests
    script: ./beam_calibration_camera_tests
    - stage: beam_defects_tests
    script: cd $HOME/catkin_ws/build/libbeam/beam_defects
    script: ./beam_defects_delam_tests
    script: ./beam_defects_spall_tests
    script: ./beam_defects_crack_tests
    script: ./beam_defects_corrosion_tests
    - stage: beam_colorize_tests
    script: cd $HOME/catkin_ws/build/libbeam/beam_colorize
    script: ./beam_colorize_tests
