# Specify xenial linux distribution and minimal language support
sudo: required
language: minimal
dist: xenial

# Setup build cache
cache:
  apt: true
  ccache: true
  directories:
    - $HOME/.ccache
    - /tmp/beam_dependencies

# Set global variables
env:
  global:
    - CI_SOURCE_PATH=$(pwd)
    - CONTINUOUS_INTEGRATION='True'

# Check installation script
install:
  - cd $CI_SOURCE_PATH
  - travis_wait 120 bash ./scripts/install.bash

# Run unit test scripts
script:
  - cd $HOME/catkin_ws/build/libbeam
  - bash ./beam_calibration/run_all_tests.sh
  - cd $HOME/catkin_ws/build/libbeam/beam_defects
  - ./beam_defects_delam_tests
  - ./beam_defects_spall_tests
  - ./beam_defects_crack_tests
  - ./beam_defects_corrosion_tests
  - cd $HOME/catkin_ws/build/libbeam/beam_colorize
  - ./beam_colorize_tests
  - cd $HOME/catkin_ws/build/libbeam/beam_cv
  - ./beam_cv_utils_tests
  - ./beam_cv_depth_tests
