# Specify generic linux distribution of linux
sudo: required
language: generic
dist: xenial

# Setup build cache
cache:
  apt: true
  ccache: true
  directories:
    - $HOME/.ccache
    - /tmp/beam_dependencies

# Set global variables
env:
  global:
    - CI_SOURCE_PATH=$(pwd)
    - CONTINUOUS_INTEGRATION='True'

# Check installation script
install:
  - cd $CI_SOURCE_PATH
  - travis_wait 120 bash ./scripts/install.bash

# Run unit test scripts
script:
  - cd $HOME/catkin_ws/build/libbeam/beam_calibration
  - ./beam_calibration_extrinsics_tests
  - ./beam_calibration_camera_tests
  - cd $HOME/catkin_ws/build/libbeam/beam_defects
  - ./beam_defects_delam_tests
  - ./beam_defects_spall_tests
  - ./beam_defects_crack_tests
  - ./beam_defects_corrosion_tests
  - cd $HOME/catkin_ws/build/libbeam/beam_colorize
  - ./beam_colorize_tests
