sudo: required
cache:
  apt: true
  ccache: true
  directories:
    - $HOME/.ccache
    - /tmp/beam_dependencies
# Specify what combinations of Ubuntu/ROS we want to build
# Limited to what is available on Travis VMs.
language: generic
matrix:
  allow_failures:
    - env: CHECK_COMMIT_FORMAT=ON
  include:
    - name: "Xenial kinetic"
      dist: xenial
      env: ROS_DISTRO=kinetic

# Configuration variables. All variables are global now, but this can be used to
# trigger a build matrix for different ROS distributions if desired.
env:
  global:
    - ROS_CI_DESKTOP="`lsb_release -cs`"  # e.g. [precise|trusty|...]
    - CI_SOURCE_PATH=$(pwd)
    - ROSINSTALL_FILE=$CI_SOURCE_PATH/dependencies.rosinstall
    - CATKIN_OPTIONS=$CI_SOURCE_PATH/catkin.options
    - ROS_PARALLEL_JOBS='-j8 -l6'
    # Set the python path manually to include /usr/-/python2.7/dist-packages
    # as this is where apt-get installs python packages.
    - PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages
################################################################################
before_install:
  - sudo apt-get install libflann*
  - cd $CI_SOURCE_PATH
  - bash ./scripts/install.bash
# Install barebones ROS setup.
script:
  - cd $CI_SOURCE_PATH
  - bash ./scripts/install.bash
  - ./beam_defects_delam_tests --success
  - ./beam_defects_spall_tests --success
