# find packages
# Create interfaces for importing all ROS
IF(NOT TARGET roscpp::roscpp)
  ADD_LIBRARY(roscpp::roscpp INTERFACE IMPORTED)
  SET_TARGET_PROPERTIES(roscpp::roscpp PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${roscpp_INCLUDE_DIRS}"
    INTERFACE_LINK_LIBRARIES "${roscpp_LIBRARIES}")
ENDIF()

IF(NOT TARGET tf2::tf2)
  ADD_LIBRARY(tf2::tf2 INTERFACE IMPORTED)
  SET_TARGET_PROPERTIES(tf2::tf2 PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${tf2_INCLUDE_DIRS}"
    INTERFACE_LINK_LIBRARIES "${tf2_LIBRARIES}")
ENDIF()


IF(NOT TARGET rosbag::rosbag)
  ADD_LIBRARY(rosbag::rosbag INTERFACE IMPORTED)
  SET_TARGET_PROPERTIES(rosbag::rosbag PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${rosbag_INCLUDE_DIRS}"
    INTERFACE_LINK_LIBRARIES "${rosbag_LIBRARIES}")
ENDIF()

