# - Fixes imported target for opencv

IF(NOT TARGET OpenCV::OpenCV)
  ADD_LIBRARY(OpenCV::OpenCV INTERFACE IMPORTED)
  SET_PROPERTY(TARGET OpenCV::OpenCV PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES "${OpenCV_INCLUDE_DIRS}")
ENDIF()
